/**
 * Build-time loader for ../corpus-manifest.md frontmatter. The manifest is
 * regenerated by the kit's collator script; the splash renders its summary
 * stats from the YAML so the homepage numbers are alive, never hardcoded.
 *
 * Fields surfaced (per the manifest schema):
 *   summary.total_files           → e.g. 583
 *   summary.by_bucket.stub        → e.g. 210
 *   summary.by_bucket.idea-started→ e.g. 263
 *   summary.by_bucket.worked-on   → e.g. 110
 *   date_generated                → ISO date
 *
 * The repo count (28) is computed from the corpus collection itself, since
 * it's not in the manifest's frontmatter — see `loadCorpusStats` consumers.
 */

import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

export interface ManifestStats {
  total_files: number;
  worked_on: number;
  idea_started: number;
  stub: number;
  without_frontmatter?: number;
  date_generated?: string;
}

/** Parse the YAML frontmatter block from a markdown file. Cheap hand-rolled
 *  parser sufficient for the manifest's flat-keyed structure (one or two
 *  levels of nesting). Avoids pulling a YAML dep just for one file. */
function parseFrontmatter(text: string): Record<string, unknown> {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const body = match[1];
  const out: Record<string, unknown> = {};
  const stack: { obj: Record<string, unknown>; indent: number }[] = [{ obj: out, indent: -1 }];
  for (const rawLine of body.split(/\r?\n/)) {
    if (!rawLine.trim() || rawLine.trim().startsWith('#')) continue;
    if (rawLine.trimStart().startsWith('-')) continue;
    const indent = rawLine.length - rawLine.trimStart().length;
    while (stack.length > 1 && indent <= stack[stack.length - 1].indent) stack.pop();
    const line = rawLine.trim();
    const colon = line.indexOf(':');
    if (colon === -1) continue;
    const key = line.slice(0, colon).trim();
    const rawVal = line.slice(colon + 1).trim();
    const parent = stack[stack.length - 1].obj;
    if (rawVal === '') {
      const child: Record<string, unknown> = {};
      parent[key] = child;
      stack.push({ obj: child, indent });
    } else {
      parent[key] = coerce(rawVal);
    }
  }
  return out;
}

function coerce(s: string): unknown {
  const stripped = s.replace(/^['"]|['"]$/g, '');
  if (/^-?\d+$/.test(stripped)) return Number(stripped);
  if (/^-?\d+\.\d+$/.test(stripped)) return Number(stripped);
  if (stripped === 'true') return true;
  if (stripped === 'false') return false;
  return stripped;
}

let cached: ManifestStats | null = null;

export async function loadManifestStats(): Promise<ManifestStats> {
  if (cached) return cached;
  const path = resolve(process.cwd(), '..', 'corpus-manifest.md');
  try {
    const text = await readFile(path, 'utf8');
    const fm = parseFrontmatter(text) as any;
    const summary = fm.summary || {};
    const buckets = summary.by_bucket || {};
    cached = {
      total_files: Number(summary.total_files) || 0,
      worked_on: Number(buckets['worked-on']) || 0,
      idea_started: Number(buckets['idea-started']) || 0,
      stub: Number(buckets.stub) || 0,
      without_frontmatter: Number(summary.without_frontmatter) || undefined,
      date_generated: fm.date_generated,
    };
  } catch {
    cached = { total_files: 0, worked_on: 0, idea_started: 0, stub: 0 };
  }
  return cached;
}
